#!/usr/bin/env python3
"""Generate agent instruction files from the shared rules source."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


GENERATED_NOTICE = "<!-- Generated by scripts/generate-rules.py; edit source files instead. -->"

TASK_REFERENCES = """## Dynamic Skill Auto-Discovery

For task-specific workflow capsules, check [SKILL-REFERENCE.md](SKILL-REFERENCE.md) and load the matching [skills/](skills/) `SKILL.md` only when the task matches its trigger.

Read the relevant standard before executing when the user's request involves:

- **Tests/TDD:** [ai-agent-standards/engineering-practices/TESTING_STANDARDS.md](ai-agent-standards/engineering-practices/TESTING_STANDARDS.md)
- **Security/Auth/Secrets:** [ai-agent-standards/risk-management/security-constraints.md](ai-agent-standards/risk-management/security-constraints.md)
- **Performance/Database/Caching:** [ai-agent-standards/engineering-practices/NON_FUNCTIONAL_REQUIREMENTS.md](ai-agent-standards/engineering-practices/NON_FUNCTIONAL_REQUIREMENTS.md)
- **UI/Accessibility:** [ai-agent-standards/compliance/A11Y_CHECKLIST.md](ai-agent-standards/compliance/A11Y_CHECKLIST.md)
- **Release/Git/CI:** [ai-agent-standards/engineering-practices/RELEASE_PROCESS.md](ai-agent-standards/engineering-practices/RELEASE_PROCESS.md)
- **Docs/README/Changelog:** [ai-agent-standards/engineering-practices/DOCUMENTATION_STANDARDS.md](ai-agent-standards/engineering-practices/DOCUMENTATION_STANDARDS.md)
- **Compliance/Audit:** [ai-agent-standards/compliance/COMPLIANCE.md](ai-agent-standards/compliance/COMPLIANCE.md)"""

VERIFICATION = """When asked "What coding standards are you following?" or "/standards", respond:

> AI-Coding-Standards v2.6.0 with 6 Core Principles active.
> Framework: Controlled AI-Assisted Development
> Principles: (1) Think Before Coding, (2) Simplicity First, (3) Surgical Changes, (4) Goal-Driven Execution, (5) DRY & Reusability, (6) Code Organization"""


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def load_manifest(root: Path) -> list[dict]:
    manifest = json.loads(read_text(root / "rules" / "agent-manifest.json"))
    agents = manifest.get("agents", [])
    if not isinstance(agents, list) or not agents:
        raise ValueError("rules/agent-manifest.json must contain a non-empty agents list")
    return agents


def extract_core_principles(principles_md: str) -> str:
    start = principles_md.index("## 1. Think Before Coding")
    end = principles_md.index("---", start)
    return principles_md[start:end].strip()


def render_frontmatter(values: dict | None) -> str:
    if not values:
        return ""
    lines = ["---"]
    for key, value in values.items():
        if isinstance(value, bool):
            rendered = "true" if value else "false"
        else:
            rendered = str(value)
        lines.append(f"{key}: {rendered}")
    lines.append("---")
    return "\n".join(lines)


def render_agent(root: Path, agent: dict, core_principles: str) -> tuple[Path, str]:
    template_path = root / "rules" / "templates" / agent["template"]
    rendered = read_text(template_path)
    output = agent["output"]
    replacements = {
        "output": output,
        "label": agent["label"],
        "core_principles": core_principles,
        "generated_notice": GENERATED_NOTICE,
        "task_references": TASK_REFERENCES,
        "verification": VERIFICATION,
        "frontmatter": render_frontmatter(agent.get("frontmatter")),
    }
    for key, value in replacements.items():
        rendered = rendered.replace("{{" + key + "}}", value)
    return root / output, rendered.rstrip() + "\n"


def render_all(root: Path, agent_key: str | None = None) -> dict[Path, str]:
    agents = load_manifest(root)
    if agent_key:
        agents = [agent for agent in agents if agent["key"] == agent_key]
        if not agents:
            valid = ", ".join(agent["key"] for agent in load_manifest(root))
            raise ValueError(f"Unknown agent '{agent_key}'. Valid choices: {valid}")

    core_principles = extract_core_principles(read_text(root / "karpathy" / "principles.md"))
    return dict(render_agent(root, agent, core_principles) for agent in agents)


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Generated {path}")


def check_outputs(outputs: dict[Path, str]) -> int:
    drifted = []
    for path, expected in outputs.items():
        if not path.exists() or read_text(path) != expected:
            drifted.append(path)
    if drifted:
        print("Generated rule files are out of date:")
        for path in drifted:
            print(f"  {path}")
        print("Run: python scripts/generate-rules.py")
        return 1
    print("Generated rule files are up to date.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate AI agent instruction files.")
    parser.add_argument("--agent", help="Generate one agent by manifest key.")
    parser.add_argument("--check", action="store_true", help="Fail if generated files are out of date.")
    args = parser.parse_args(argv)

    root = repo_root()
    try:
        outputs = render_all(root, args.agent)
    except (KeyError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    if args.check:
        return check_outputs(outputs)
    write_outputs(outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
